// Curated first-party publisher and project feeds. Feed availability checked in September 2026.
// A successful feed check is not independent fact checking or proof of human authorship.
export const ADDITIONAL_SOURCES = [
  {
    id: 'google-research',
    name: 'Google Research',
    category: 'Research',
    kind: 'publisher',
    url: 'https://research.google/blog/rss/',
    hosts: ['research.google'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:22.174Z',
  },
  {
    id: 'microsoft-ai',
    name: 'Microsoft Cloud Blog',
    category: 'AI announcements',
    kind: 'publisher',
    url: 'https://www.microsoft.com/en-us/microsoft-cloud/blog/feed//',
    hosts: ['www.microsoft.com', 'microsoft.com'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:22.189Z',
  },
  {
    id: 'google-developers',
    name: 'Google Developers',
    category: 'Developer news',
    kind: 'publisher',
    url: 'https://developers.googleblog.com/feeds/posts/default/',
    hosts: ['developers.googleblog.com'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:23.124Z',
  },
  {
    id: 'microsoft-research',
    name: 'Microsoft Research',
    category: 'Research',
    kind: 'publisher',
    url: 'https://www.microsoft.com/en-us/research/feed/',
    hosts: ['www.microsoft.com', 'microsoft.com'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:23.188Z',
  },
  {
    id: 'aws-ml',
    name: 'AWS Machine Learning',
    category: 'AI infrastructure',
    kind: 'publisher',
    url: 'https://aws.amazon.com/blogs/machine-learning/feed/',
    hosts: ['aws.amazon.com'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:23.669Z',
  },
  {
    id: 'apple-ml',
    name: 'Apple Machine Learning Research',
    category: 'Research',
    kind: 'publisher',
    url: 'https://machinelearning.apple.com/rss.xml',
    hosts: ['machinelearning.apple.com'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:24.032Z',
  },
  {
    id: 'mit-ai',
    name: 'MIT News — Artificial Intelligence',
    category: 'Research',
    kind: 'publisher',
    url: 'https://news.mit.edu/rss/topic/artificial-intelligence2',
    hosts: ['news.mit.edu'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:24.231Z',
  },
  {
    id: 'nvidia-developer',
    name: 'NVIDIA Developer',
    category: 'AI infrastructure',
    kind: 'publisher',
    url: 'https://developer.nvidia.com/blog/feed/',
    hosts: ['developer.nvidia.com'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:24.388Z',
  },
  {
    id: 'bair',
    name: 'Berkeley AI Research',
    category: 'Research',
    kind: 'publisher',
    url: 'https://bair.berkeley.edu/blog/feed.xml',
    hosts: ['bair.berkeley.edu'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:25.040Z',
  },
  {
    id: 'pytorch-blog',
    name: 'PyTorch Blog',
    category: 'AI engineering',
    kind: 'publisher',
    url: 'https://pytorch.org/blog/feed/',
    hosts: ['pytorch.org'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:25.188Z',
  },
  {
    id: 'cloudflare-blog',
    name: 'Cloudflare Blog',
    category: 'AI infrastructure',
    kind: 'publisher',
    url: 'https://blog.cloudflare.com/rss/',
    hosts: ['blog.cloudflare.com'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:25.325Z',
  },
  {
    id: 'mozilla-ai',
    name: 'Mozilla AI',
    category: 'AI engineering',
    kind: 'publisher',
    url: 'https://blog.mozilla.ai/rss/',
    hosts: ['blog.mozilla.ai'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:25.507Z',
  },
  {
    id: 'mozilla-blog',
    name: 'Mozilla Blog',
    category: 'Technology research',
    kind: 'publisher',
    url: 'https://blog.mozilla.org/en/feed/',
    hosts: ['blog.mozilla.org'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:25.640Z',
  },
  {
    id: 'tensorflow-blog',
    name: 'TensorFlow Blog',
    category: 'AI engineering',
    kind: 'publisher',
    url: 'https://blog.tensorflow.org/feeds/posts/default',
    hosts: ['blog.tensorflow.org'],
    aiOnly: true,
    color: '#527aaa',
    feedCheckedAt: '2026-09-29T19:03:25.808Z',
  },
  {
    id: 'release-tensorflow-tensorflow',
    name: 'TensorFlow releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/tensorflow/tensorflow/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'tensorflow/tensorflow',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:26.478Z',
  },
  {
    id: 'release-jax-ml-jax',
    name: 'JAX releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/jax-ml/jax/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'jax-ml/jax',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:26.702Z',
  },
  {
    id: 'release-scikit-learn-scikit-learn',
    name: 'scikit-learn releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/scikit-learn/scikit-learn/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'scikit-learn/scikit-learn',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:27.146Z',
  },
  {
    id: 'release-pytorch-pytorch',
    name: 'PyTorch releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/pytorch/pytorch/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'pytorch/pytorch',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:27.219Z',
  },
  {
    id: 'release-keras-team-keras',
    name: 'Keras releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/keras-team/keras/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'keras-team/keras',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:27.562Z',
  },
  {
    id: 'release-dmlc-xgboost',
    name: 'XGBoost releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/dmlc/xgboost/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'dmlc/xgboost',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:27.722Z',
  },
  {
    id: 'release-catboost-catboost',
    name: 'CatBoost releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/catboost/catboost/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'catboost/catboost',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:28.157Z',
  },
  {
    id: 'release-lightning-ai-pytorch-lightning',
    name: 'PyTorch Lightning releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/Lightning-AI/pytorch-lightning/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'Lightning-AI/pytorch-lightning',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:28.992Z',
  },
  {
    id: 'release-microsoft-lightgbm',
    name: 'LightGBM releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/lightgbm-org/LightGBM/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'lightgbm-org/LightGBM',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:29.183Z',
  },
  {
    id: 'release-huggingface-transformers',
    name: 'Transformers releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/transformers/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/transformers',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:29.990Z',
  },
  {
    id: 'release-huggingface-accelerate',
    name: 'Accelerate releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/accelerate/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/accelerate',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:30.049Z',
  },
  {
    id: 'release-huggingface-peft',
    name: 'PEFT releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/peft/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/peft',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:31.364Z',
  },
  {
    id: 'release-huggingface-diffusers',
    name: 'Diffusers releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/diffusers/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/diffusers',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:31.600Z',
  },
  {
    id: 'release-huggingface-datasets',
    name: 'Datasets releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/datasets/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/datasets',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:32.099Z',
  },
  {
    id: 'release-huggingface-tokenizers',
    name: 'Tokenizers releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/tokenizers/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/tokenizers',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:32.230Z',
  },
  {
    id: 'release-huggingface-trl',
    name: 'TRL releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/trl/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/trl',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:32.286Z',
  },
  {
    id: 'release-huggingface-huggingface-hub',
    name: 'Hugging Face Hub releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/huggingface_hub/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/huggingface_hub',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:33.014Z',
  },
  {
    id: 'release-huggingface-optimum',
    name: 'Optimum releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/optimum/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/optimum',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:33.038Z',
  },
  {
    id: 'release-huggingface-safetensors',
    name: 'Safetensors releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/safetensors/safetensors/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'safetensors/safetensors',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:33.514Z',
  },
  {
    id: 'release-huggingface-smolagents',
    name: 'Smolagents releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/smolagents/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/smolagents',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:34.072Z',
  },
  {
    id: 'release-ollama-ollama',
    name: 'Ollama releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/ollama/ollama/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'ollama/ollama',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:34.114Z',
  },
  {
    id: 'release-ukplab-sentence-transformers',
    name: 'Sentence Transformers releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/sentence-transformers/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/sentence-transformers',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:34.166Z',
  },
  {
    id: 'release-ggml-org-whisper-cpp',
    name: 'whisper.cpp releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/ggml-org/whisper.cpp/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'ggml-org/whisper.cpp',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:34.935Z',
  },
  {
    id: 'release-ggml-org-llama-cpp',
    name: 'llama.cpp releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/ggml-org/llama.cpp/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'ggml-org/llama.cpp',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:35.039Z',
  },
  {
    id: 'release-vllm-project-vllm',
    name: 'vLLM releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/vllm-project/vllm/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'vllm-project/vllm',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:36.300Z',
  },
  {
    id: 'release-sgl-project-sglang',
    name: 'SGLang releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/sgl-project/sglang/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'sgl-project/sglang',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:37.295Z',
  },
  {
    id: 'release-berriai-litellm',
    name: 'LiteLLM releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/BerriAI/litellm/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'BerriAI/litellm',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:37.543Z',
  },
  {
    id: 'release-nvidia-tensorrt',
    name: 'TensorRT releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/NVIDIA/TensorRT/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'NVIDIA/TensorRT',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:37.787Z',
  },
  {
    id: 'release-nvidia-nemo-guardrails',
    name: 'NeMo Guardrails releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/NVIDIA-NeMo/Guardrails/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'NVIDIA-NeMo/Guardrails',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:38.711Z',
  },
  {
    id: 'release-nvidia-tensorrt-llm',
    name: 'TensorRT-LLM releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/NVIDIA/TensorRT-LLM/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'NVIDIA/TensorRT-LLM',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:38.897Z',
  },
  {
    id: 'release-nvidia-nemo',
    name: 'NeMo releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/NVIDIA-NeMo/Speech/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'NVIDIA-NeMo/Speech',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:39.045Z',
  },
  {
    id: 'release-triton-inference-server-server',
    name: 'Triton Inference Server releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/triton-inference-server/server/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'triton-inference-server/server',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:39.350Z',
  },
  {
    id: 'release-triton-lang-triton',
    name: 'Triton compiler releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/triton-lang/triton/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'triton-lang/triton',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:39.545Z',
  },
  {
    id: 'release-microsoft-onnxruntime',
    name: 'ONNX Runtime releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/microsoft/onnxruntime/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'microsoft/onnxruntime',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:40.059Z',
  },
  {
    id: 'release-openvinotoolkit-openvino',
    name: 'OpenVINO releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/openvinotoolkit/openvino/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'openvinotoolkit/openvino',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:40.102Z',
  },
  {
    id: 'release-ml-explore-mlx-lm',
    name: 'MLX LM releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/ml-explore/mlx-lm/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'ml-explore/mlx-lm',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:41.044Z',
  },
  {
    id: 'release-onnx-onnx',
    name: 'ONNX releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/onnx/onnx/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'onnx/onnx',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:41.449Z',
  },
  {
    id: 'release-apple-coremltools',
    name: 'Core ML Tools releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/apple/coremltools/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'apple/coremltools',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:41.579Z',
  },
  {
    id: 'release-ml-explore-mlx',
    name: 'MLX releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/ml-explore/mlx/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'ml-explore/mlx',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:41.893Z',
  },
  {
    id: 'release-pytorch-ao',
    name: 'TorchAO releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/pytorch/ao/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'pytorch/ao',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:42.409Z',
  },
  {
    id: 'release-pytorch-torchtune',
    name: 'Torchtune releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/meta-pytorch/torchtune/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'meta-pytorch/torchtune',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:42.823Z',
  },
  {
    id: 'release-microsoft-deepspeed',
    name: 'DeepSpeed releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/deepspeedai/DeepSpeed/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'deepspeedai/DeepSpeed',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:42.870Z',
  },
  {
    id: 'release-dao-ailab-flash-attention',
    name: 'FlashAttention releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/Dao-AILab/flash-attention/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'Dao-AILab/flash-attention',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:43.604Z',
  },
  {
    id: 'release-flashinfer-ai-flashinfer',
    name: 'FlashInfer releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/flashinfer-ai/flashinfer/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'flashinfer-ai/flashinfer',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:44.063Z',
  },
  {
    id: 'release-bitsandbytes-foundation-bitsandbytes',
    name: 'Bitsandbytes releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'bitsandbytes-foundation/bitsandbytes',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:44.079Z',
  },
  {
    id: 'release-openai-openai-python',
    name: 'OpenAI Python SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/openai/openai-python/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'openai/openai-python',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:44.280Z',
  },
  {
    id: 'release-openai-openai-node',
    name: 'OpenAI JavaScript SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/openai/openai-node/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'openai/openai-node',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:45.095Z',
  },
  {
    id: 'release-openai-whisper',
    name: 'Whisper releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/openai/whisper/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'openai/whisper',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:45.420Z',
  },
  {
    id: 'release-openai-openai-agents-python',
    name: 'OpenAI Agents SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/openai/openai-agents-python/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'openai/openai-agents-python',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:45.468Z',
  },
  {
    id: 'release-openai-codex',
    name: 'Codex CLI releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/openai/codex/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'openai/codex',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:45.471Z',
  },
  {
    id: 'release-anthropics-claude-code',
    name: 'Claude Code releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/anthropics/claude-code/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'anthropics/claude-code',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:45.978Z',
  },
  {
    id: 'release-anthropics-anthropic-sdk-typescript',
    name: 'Anthropic TypeScript SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/anthropics/anthropic-sdk-typescript/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'anthropics/anthropic-sdk-typescript',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:46.008Z',
  },
  {
    id: 'release-anthropics-anthropic-sdk-python',
    name: 'Anthropic Python SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/anthropics/anthropic-sdk-python/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'anthropics/anthropic-sdk-python',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:46.016Z',
  },
  {
    id: 'release-googleapis-python-genai',
    name: 'Google Gen AI Python SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/googleapis/python-genai/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'googleapis/python-genai',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:46.477Z',
  },
  {
    id: 'release-googleapis-js-genai',
    name: 'Google Gen AI JavaScript SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/googleapis/js-genai/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'googleapis/js-genai',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:46.485Z',
  },
  {
    id: 'release-google-gemini-gemini-cli',
    name: 'Gemini CLI releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/google-gemini/gemini-cli/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'google-gemini/gemini-cli',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:46.807Z',
  },
  {
    id: 'release-mistralai-client-python',
    name: 'Mistral Python SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/mistralai/client-python/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'mistralai/client-python',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:46.938Z',
  },
  {
    id: 'release-google-adk-python',
    name: 'Google Agent Development Kit releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/google/adk-python/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'google/adk-python',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:47.145Z',
  },
  {
    id: 'release-cohere-ai-cohere-python',
    name: 'Cohere Python SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/cohere-ai/cohere-python/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'cohere-ai/cohere-python',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:47.471Z',
  },
  {
    id: 'release-groq-groq-python',
    name: 'Groq Python SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/groq/groq-python/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'groq/groq-python',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:47.503Z',
  },
  {
    id: 'release-modelcontextprotocol-python-sdk',
    name: 'MCP Python SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/modelcontextprotocol/python-sdk/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'modelcontextprotocol/python-sdk',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:47.871Z',
  },
  {
    id: 'release-modelcontextprotocol-typescript-sdk',
    name: 'MCP TypeScript SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/modelcontextprotocol/typescript-sdk/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'modelcontextprotocol/typescript-sdk',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:48.193Z',
  },
  {
    id: 'release-modelcontextprotocol-inspector',
    name: 'MCP Inspector releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/modelcontextprotocol/inspector/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'modelcontextprotocol/inspector',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:48.630Z',
  },
  {
    id: 'release-langchain-ai-langchain',
    name: 'LangChain releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/langchain-ai/langchain/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'langchain-ai/langchain',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:48.894Z',
  },
  {
    id: 'release-langchain-ai-langgraph',
    name: 'LangGraph releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/langchain-ai/langgraph/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'langchain-ai/langgraph',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:49.023Z',
  },
  {
    id: 'release-langchain-ai-langchainjs',
    name: 'LangChain.js releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/langchain-ai/langchainjs/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'langchain-ai/langchainjs',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:49.486Z',
  },
  {
    id: 'release-microsoft-autogen',
    name: 'AutoGen releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/microsoft/autogen/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'microsoft/autogen',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:49.865Z',
  },
  {
    id: 'release-run-llama-llama-index',
    name: 'LlamaIndex releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/run-llama/llama_index/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'run-llama/llama_index',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:50.261Z',
  },
  {
    id: 'release-crewaiinc-crewai',
    name: 'CrewAI releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/crewAIInc/crewAI/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'crewAIInc/crewAI',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:50.287Z',
  },
  {
    id: 'release-microsoft-semantic-kernel',
    name: 'Semantic Kernel releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/microsoft/semantic-kernel/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'microsoft/semantic-kernel',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:50.412Z',
  },
  {
    id: 'release-pydantic-pydantic-ai',
    name: 'Pydantic AI releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/pydantic/pydantic-ai/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'pydantic/pydantic-ai',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:51.486Z',
  },
  {
    id: 'release-deepset-ai-haystack',
    name: 'Haystack releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/deepset-ai/haystack/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'deepset-ai/haystack',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:51.945Z',
  },
  {
    id: 'release-stanfordnlp-dspy',
    name: 'DSPy releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/stanfordnlp/dspy/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'stanfordnlp/dspy',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:52.094Z',
  },
  {
    id: 'release-guidance-ai-guidance',
    name: 'Guidance releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/guidance-ai/guidance/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'guidance-ai/guidance',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:52.098Z',
  },
  {
    id: 'release-dottxt-ai-outlines',
    name: 'Outlines releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/dottxt-ai/outlines/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'dottxt-ai/outlines',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:52.739Z',
  },
  {
    id: 'release-guardrails-ai-guardrails',
    name: 'Guardrails AI releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/guardrails-ai/guardrails/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'guardrails-ai/guardrails',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:52.910Z',
  },
  {
    id: 'release-instructor-ai-instructor',
    name: 'Instructor releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/567-labs/instructor/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: '567-labs/instructor',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:53.123Z',
  },
  {
    id: 'release-confident-ai-deepeval',
    name: 'DeepEval releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/confident-ai/deepeval/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'confident-ai/deepeval',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:53.361Z',
  },
  {
    id: 'release-promptfoo-promptfoo',
    name: 'Promptfoo releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/promptfoo/promptfoo/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'promptfoo/promptfoo',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:53.734Z',
  },
  {
    id: 'release-explodinggradients-ragas',
    name: 'Ragas releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/vibrantlabsai/ragas/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'vibrantlabsai/ragas',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:54.232Z',
  },
  {
    id: 'release-eleutherai-lm-evaluation-harness',
    name: 'LM Evaluation Harness releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/EleutherAI/lm-evaluation-harness/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'EleutherAI/lm-evaluation-harness',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:54.569Z',
  },
  {
    id: 'release-wandb-wandb',
    name: 'Weights & Biases SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/wandb/wandb/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'wandb/wandb',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:55.082Z',
  },
  {
    id: 'release-mlflow-mlflow',
    name: 'MLflow releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/mlflow/mlflow/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'mlflow/mlflow',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:55.203Z',
  },
  {
    id: 'release-bentoml-bentoml',
    name: 'BentoML releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/bentoml/BentoML/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'bentoml/BentoML',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:55.908Z',
  },
  {
    id: 'release-seldonio-seldon-core',
    name: 'Seldon Core releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/SeldonIO/seldon-core/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'SeldonIO/seldon-core',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:56.210Z',
  },
  {
    id: 'release-kubeflow-trainer',
    name: 'Kubeflow Trainer releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/kubeflow/trainer/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'kubeflow/trainer',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:57.124Z',
  },
  {
    id: 'release-ray-project-ray',
    name: 'Ray releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/ray-project/ray/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'ray-project/ray',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:57.538Z',
  },
  {
    id: 'release-kubeflow-pipelines',
    name: 'Kubeflow Pipelines releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/kubeflow/pipelines/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'kubeflow/pipelines',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:57.707Z',
  },
  {
    id: 'release-feast-dev-feast',
    name: 'Feast releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/feast-dev/feast/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'feast-dev/feast',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:58.100Z',
  },
  {
    id: 'release-kedro-org-kedro',
    name: 'Kedro releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/kedro-org/kedro/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'kedro-org/kedro',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:58.253Z',
  },
  {
    id: 'release-iterative-dvc',
    name: 'DVC releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/treeverse/dvc/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'treeverse/dvc',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:58.537Z',
  },
  {
    id: 'release-zenml-io-zenml',
    name: 'ZenML releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/zenml-io/zenml/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'zenml-io/zenml',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:59.262Z',
  },
  {
    id: 'release-milvus-io-milvus',
    name: 'Milvus releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/milvus-io/milvus/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'milvus-io/milvus',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:03:59.682Z',
  },
  {
    id: 'release-qdrant-qdrant',
    name: 'Qdrant releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/qdrant/qdrant/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'qdrant/qdrant',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:00.384Z',
  },
  {
    id: 'release-chroma-core-chroma',
    name: 'Chroma releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/chroma-core/chroma/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'chroma-core/chroma',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:00.497Z',
  },
  {
    id: 'release-weaviate-weaviate',
    name: 'Weaviate releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/weaviate/weaviate/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'weaviate/weaviate',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:00.639Z',
  },
  {
    id: 'release-pgvector-pgvector',
    name: 'pgvector releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/pgvector/pgvector/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'pgvector/pgvector',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:00.979Z',
  },
  {
    id: 'release-lancedb-lancedb',
    name: 'LanceDB releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/lancedb/lancedb/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'lancedb/lancedb',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:01.032Z',
  },
  {
    id: 'release-vespa-engine-vespa',
    name: 'Vespa releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/vespa-engine/vespa/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'vespa-engine/vespa',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:01.647Z',
  },
  {
    id: 'release-gradio-app-gradio',
    name: 'Gradio releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/gradio-app/gradio/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'gradio-app/gradio',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:01.679Z',
  },
  {
    id: 'release-facebookresearch-faiss',
    name: 'FAISS releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/facebookresearch/faiss/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'facebookresearch/faiss',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:02.117Z',
  },
  {
    id: 'release-streamlit-streamlit',
    name: 'Streamlit releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/streamlit/streamlit/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'streamlit/streamlit',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:02.195Z',
  },
  {
    id: 'release-open-webui-open-webui',
    name: 'Open WebUI releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/open-webui/open-webui/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'open-webui/open-webui',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:03.178Z',
  },
  {
    id: 'release-comfyanonymous-comfyui',
    name: 'ComfyUI releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/Comfy-Org/ComfyUI/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'Comfy-Org/ComfyUI',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:03.184Z',
  },
  {
    id: 'release-invoke-ai-invokeai',
    name: 'InvokeAI releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/invoke-ai/InvokeAI/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'invoke-ai/InvokeAI',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:03.225Z',
  },
  {
    id: 'release-opencv-opencv',
    name: 'OpenCV releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/opencv/opencv/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'opencv/opencv',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:03.964Z',
  },
  {
    id: 'release-ultralytics-ultralytics',
    name: 'Ultralytics YOLO releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/ultralytics/ultralytics/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'ultralytics/ultralytics',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:04.392Z',
  },
  {
    id: 'release-automatic1111-stable-diffusion-webui',
    name: 'Stable Diffusion WebUI releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'AUTOMATIC1111/stable-diffusion-webui',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:04.778Z',
  },
  {
    id: 'release-roboflow-supervision',
    name: 'Supervision releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/roboflow/supervision/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'roboflow/supervision',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:05.094Z',
  },
  {
    id: 'release-roboflow-inference',
    name: 'Roboflow Inference releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/roboflow/inference/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'roboflow/inference',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:05.264Z',
  },
  {
    id: 'release-open-mmlab-mmdetection',
    name: 'MMDetection releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/open-mmlab/mmdetection/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'open-mmlab/mmdetection',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:05.556Z',
  },
  {
    id: 'release-paddlepaddle-paddleocr',
    name: 'PaddleOCR releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/PaddlePaddle/PaddleOCR/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'PaddlePaddle/PaddleOCR',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:05.861Z',
  },
  {
    id: 'release-open-mmlab-mmsegmentation',
    name: 'MMSegmentation releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/open-mmlab/mmsegmentation/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'open-mmlab/mmsegmentation',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:06.019Z',
  },
  {
    id: 'release-docling-project-docling',
    name: 'Docling releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/docling-project/docling/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'docling-project/docling',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:06.831Z',
  },
  {
    id: 'release-unstructured-io-unstructured',
    name: 'Unstructured releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/Unstructured-IO/unstructured/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'Unstructured-IO/unstructured',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:06.838Z',
  },
  {
    id: 'release-google-deepmind-mujoco',
    name: 'MuJoCo releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/google-deepmind/mujoco/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'google-deepmind/mujoco',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:07.441Z',
  },
  {
    id: 'release-isaac-sim-isaaclab',
    name: 'Isaac Lab releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/isaac-sim/IsaacLab/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'isaac-sim/IsaacLab',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:08.039Z',
  },
  {
    id: 'release-paddlepaddle-paddle',
    name: 'PaddlePaddle releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/PaddlePaddle/Paddle/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'PaddlePaddle/Paddle',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:08.080Z',
  },
  {
    id: 'release-dlr-rm-stable-baselines3',
    name: 'Stable Baselines3 releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/DLR-RM/stable-baselines3/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'DLR-RM/stable-baselines3',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:08.734Z',
  },
  {
    id: 'release-huggingface-lerobot',
    name: 'LeRobot releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/huggingface/lerobot/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'huggingface/lerobot',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:08.799Z',
  },
  {
    id: 'release-farama-foundation-gymnasium',
    name: 'Gymnasium releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/Farama-Foundation/Gymnasium/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'Farama-Foundation/Gymnasium',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:09.057Z',
  },
  {
    id: 'release-systran-faster-whisper',
    name: 'Faster Whisper releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/SYSTRAN/faster-whisper/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'SYSTRAN/faster-whisper',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:09.688Z',
  },
  {
    id: 'release-farama-foundation-pettingzoo',
    name: 'PettingZoo releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/Farama-Foundation/PettingZoo/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'Farama-Foundation/PettingZoo',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:09.804Z',
  },
  {
    id: 'release-coqui-ai-tts',
    name: 'Coqui TTS releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/coqui-ai/TTS/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'coqui-ai/TTS',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:10.329Z',
  },
  {
    id: 'release-speechbrain-speechbrain',
    name: 'SpeechBrain releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/speechbrain/speechbrain/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'speechbrain/speechbrain',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:10.353Z',
  },
  {
    id: 'release-espnet-espnet',
    name: 'ESPnet releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/espnet/espnet/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'espnet/espnet',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:10.806Z',
  },
  {
    id: 'release-k2-fsa-sherpa-onnx',
    name: 'Sherpa ONNX releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/k2-fsa/sherpa-onnx/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'k2-fsa/sherpa-onnx',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:11.199Z',
  },
  {
    id: 'release-google-deepmind-optax',
    name: 'Optax releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/google-deepmind/optax/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'google-deepmind/optax',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:11.615Z',
  },
  {
    id: 'release-google-flax',
    name: 'Flax releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/google/flax/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'google/flax',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:11.802Z',
  },
  {
    id: 'release-facebookresearch-hydra',
    name: 'Hydra releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/hydra-ecosystem/hydra/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'hydra-ecosystem/hydra',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:12.661Z',
  },
  {
    id: 'release-optuna-optuna',
    name: 'Optuna releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/optuna/optuna/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'optuna/optuna',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:13.018Z',
  },
  {
    id: 'release-explosion-spacy',
    name: 'spaCy releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/explosion/spaCy/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'explosion/spaCy',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:13.095Z',
  },
  {
    id: 'release-optuna-optuna-dashboard',
    name: 'Optuna Dashboard releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/optuna/optuna-dashboard/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'optuna/optuna-dashboard',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:13.154Z',
  },
  {
    id: 'release-stanfordnlp-stanza',
    name: 'Stanza releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/stanfordnlp/stanza/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'stanfordnlp/stanza',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:13.705Z',
  },
  {
    id: 'release-nltk-nltk',
    name: 'NLTK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/nltk/nltk/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'nltk/nltk',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:13.872Z',
  },
  {
    id: 'release-rasahq-rasa',
    name: 'Rasa releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/RasaHQ/rasa/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'RasaHQ/rasa',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:14.032Z',
  },
  {
    id: 'release-rasahq-rasa-sdk',
    name: 'Rasa SDK releases',
    category: 'AI project releases',
    kind: 'github-release',
    url: 'https://github.com/rasaHQ/rasa-sdk/releases.atom',
    hosts: ['github.com', 'api.github.com'],
    repo: 'rasaHQ/rasa-sdk',
    color: '#657e73',
    feedCheckedAt: '2026-09-29T19:04:14.525Z',
  },
];
